---

- name: Apply Controller Configuration-as-Code
  hosts: localhost
  gather_facts: false
  become: false

  vars_files:
    - vars/controller_secrets.yml

  tasks:
    - name: Include Controller configuration files
      tags: always
      ansible.builtin.include_vars:
        dir: controller

    - name: Call dispatch role for Controller configuration
      tags: always
      ansible.builtin.include_role:
        name: infra.aap_configuration.dispatch
